layout('us')
press("CONTROL ESCAPE") 
delay(500)
type("powershell\n") 
delay(500)
press("CONTROL SHIFT ENTER") 
delay(1000)
press("LEFT") 
press("ENTER")
delay(2000) 
type("Get-EventLog -LogName System | Export-Clixml E:\\Logs\\SystemLog.xml\n")
delay(500)
type("Get-EventLog -LogName Security | Export-Clixml E:\\Logs\\SecurityLog.xml\n")
delay(500)
type("Get-EventLog -LogName Application | Export-Clixml E:\\Logs\\ApplicationLog.xml\n")
delay(500)
type("exit\n")


